services:
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://database:27017/libris-db
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # This bridges Windows 5173 to Vite's internal 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo-data:
